// src/components/EditableContent.jsx
import React, { useState, useEffect } from 'react';

const EditableContent = ({ content, onContentChange, onSaveContent }) => {
    const [editedContent, setEditedContent] = useState('');
    const [contentTitle, setContentTitle] = useState('');
    const [isSaved, setIsSaved] = useState(false);

    // Initialize the editor when content changes
    useEffect(() => {
        if (content) {
            setEditedContent(content.content);

            // Generate a default title based on content type and topic
            const contentTypeFormatted = content.contentType
                .split('-')
                .map(word => word.charAt(0).toUpperCase() + word.slice(1))
                .join(' ');

            setContentTitle(`${contentTypeFormatted} - ${content.topic}`);
        }
    }, [content]);

    // Handle content changes
    const handleContentChange = (e) => {
        setEditedContent(e.target.value);
        if (onContentChange) {
            onContentChange(e.target.value);
        }

        // Reset saved state when content changes
        setIsSaved(false);
    };

    // Handle title changes
    const handleTitleChange = (e) => {
        setContentTitle(e.target.value);
        setIsSaved(false);
    };

    // Handle saving content
    const handleSave = () => {
        if (!content) return;

        const updatedContent = {
            ...content,
            content: editedContent,
            title: contentTitle,
            lastEdited: new Date().toISOString()
        };

        // Call the save handler provided by parent
        if (onSaveContent) {
            onSaveContent(updatedContent);
        }

        // Show saved confirmation
        setIsSaved(true);
        setTimeout(() => setIsSaved(false), 3000);

        // Also save to localStorage
        const savedItems = JSON.parse(localStorage.getItem('savedEdits') || '[]');
        const existingIndex = savedItems.findIndex(item =>
            item.provider === content.provider &&
            item.topic === content.topic &&
            item.timestamp === content.timestamp
        );

        if (existingIndex >= 0) {
            // Update existing item
            savedItems[existingIndex] = updatedContent;
        } else {
            // Add new item
            savedItems.push(updatedContent);
        }

        localStorage.setItem('savedEdits', JSON.stringify(savedItems));
    };

    if (!content) {
        return (
            <div className="no-content-message">
                <p>No content selected for editing.</p>
            </div>
        );
    }

    return (
        <div className="editable-content">
            <div className="editor-header">
                <input
                    type="text"
                    value={contentTitle}
                    onChange={handleTitleChange}
                    className="content-title-input"
                    placeholder="Enter a title for your content"
                />

                <div className="content-meta">
                    <span className="model-info">
                        Originally generated by: <strong>{content.provider} / {content.model}</strong>
                    </span>
                </div>
            </div>

            <div className="editor-container">
                <textarea
                    value={editedContent}
                    onChange={handleContentChange}
                    className="content-editor"
                    placeholder="Edit your content here..."
                    rows={20}
                />
            </div>

            <div className="editor-actions">
                <div className="word-count">
                    {editedContent.split(/\s+/).filter(Boolean).length} words |
                    {editedContent.length} characters
                </div>

                <button onClick={handleSave} className="save-button">
                    {isSaved ? '✓ Saved!' : 'Save Changes'}
                </button>

                <button onClick={() => navigator.clipboard.writeText(editedContent)} className="copy-button">
                    Copy to Clipboard
                </button>
            </div>
        </div>
    );
};

export default EditableContent;